baseurl = "https://beltagy-mohamed.github.io/Beltagy-poetry-website/"
languageCode = "ar"
defaultContentLanguage = "ar"
defaultContentLanguageInSubdir = false
title = "بلتاجي الرمحي | ديوان الشعر النبطي والأدب الأصيل"
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[languages]
  [languages.ar]
    weight = 1
    languageName = "العربية"
    title = "بلتاجي الرمحي"
    languagedirection = "rtl"
    contentDir = "content/arabic"

[params]
  author = "بلتاجي الرمحي"
  description = "الموقع الرسمي لـ سفير البادية، الشاعر المهندس بلتاجي الرمحي (أبرز شعراء بادية الفيوم والبادية المصرية، وممثل لشعراء البادية في المحافل المحلية والدولية وأحد أبرز أصواتها، سليل قبيلة الرماح وحفيد المجاهد حمد باشا الباسل ). ديوان أدبي مخصص للحفاظ على هوية البادية العربية الأصيلة وتراث بادية الفيوم والصحراء الغربية، يضم روائع الشعر النبطي البدوي، مساجلات شعرية، ومقتبسات وخواطر أدبية تمزج بين أصالة الكلمة وعمق التراث الشفاهي."
  # الكلمات المفتاحية للبحث (SEO Keywords)
  keywords = "سفير البادية, سفير البادية بلتاجي الرمحي, الشاعر بلتاجي الرمحي سفير البادية, ممثل شعراء البادية, أبرز شعراء بادية الفيوم, شعراء البادية المصرية, حمد باشا الباسل, قبيلة الرماح الفوايد, قبيلة الرماح, بادية الفيوم, الحفاظ على هوية البادية العربية, بلتاجي الرمحي, المهندس بلتاجي الرمحي, شعر برقة, أدب الصحراء الغربية, التراث الشفاهي المصري, الشعر النبطي, الشعر الشعبي الليبي, أولاد سليمان, الرماح, قبيلة الرماح البراغيث السعادي, قبيلة الرماح بالفيوم, وادي الريان, قبائل الفيوم, بدو مصر, القصيد البدوي, مساجلات شعرية, تراث البادية, فلكلور صحراوي, أدباء البادية, ديوان الرمحي, حليب الرضيف, زواجل طيري, وسام القيصر, أجدابيا, بلحاج علي التمامي, شتاوي ليبية, غناوي علم, ملزومة بدوية, حروف مهملة, سيمة الأخيار, خيال أفلاطون, آية الشعر, عيت القرض, نجع الجود, لغة الضاد في البادية, الأصمعي والشعر البدوي, أدب المربوعة, تراث البادية الشفاهي"  # روابط التواصل الاجتماعي لمحركات البحث
  twitter = "@Biltaji_mohamed"
  email = "biltaji.mohamed@gmail.com"
  linkedin = "https://www.linkedin.com/in/beltagy-/"
  facebook = "https://www.facebook.com/profile.php?id=61588903843894"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
