baseurl = "https://beltagy-mohamed.github.io/Beltagy-poetry-website/"
languageCode = "ar"
defaultContentLanguage = "ar"
defaultContentLanguageInSubdir = false
title = "بلتاجي الرمحي | ديوان الشعر النبطي والأدب الأصيل"
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[languages]
  [languages.ar]
    weight = 1
    languageName = "العربية"
    title = "بلتاجي الرمحي"
    languagedirection = "rtl"
    contentDir = "content/arabic"

[params]
  author = "بلتاجي الرمحي"
  description = "ديوان الشاعر المهندس بلتاجي الرمحي: منصة رسمية لتوثيق الشعر النبطي البدوي وتراث قبائل الصحراء الغربية بمصر وبادية الفيوم. نُبحر في أدب برقة، والتراث الشفاهي للصحراء الغربية بمصر، نحاول إثراء الأدب البدوي الأصيل ."
  # الكلمات المفتاحية للبحث (SEO Keywords)
  keywords = "بلتاجي الرمحي, المهندس بلتاجي الرمحي, قبيلة الرماح, بادية الفيوم, شعر برقة, أدب الصحراء الغربية, التراث الشفاهي المصري, الشعر النبطي, الشعر الشعبي الليبي, أولاد سليمان, وادي الريان, قبائل الفيوم, بدو مصر, القصيد البدوي, مساجلات شعرية, تراث البادية, فلكلور صحراوي, أدباء البادية, ديوان الرمحي"
  
  # روابط التواصل الاجتماعي لمحركات البحث
  twitter = "@Biltaji_mohamed"
  email = "biltaji.mohamed@gmail.com"
  linkedin = "https://www.linkedin.com/in/beltagy-/"

[outputs]
  home = ["HTML", "JSON"]
